theme: askclass-course-theme

title: "Shakespeare's Sonnets"
description: >
  Dive into Shakespeare's 154 timeless sonnets with our dedicated study and memorization platform.
  Explore line-by-line analyses, thematic groupings,
  famous quotes like \"Shall I compare thee to a summer's day?\", tools for deep reading,
  and proven techniques to memorize these masterpieces of love, time, and beauty.
  Perfect for students, educators, actors, and poetry lovers seeking to master the Bard's profound verse.

acc:
  short_name: "Sonnets"
  color:
    theme: "#28170b"
    bg: "#f4e3d7"
  url: "https://sonnets.nissi.app"
  categories:
    - education
  shortcuts:
    - name: Introduction
      url: https://sonnets.nissi.app/session/intro
      desc: Introduction to Shakespeare's Sonnets
  meta:
    apple_icon: "logo-square-300.png"
    og_image: "logo-square-512.png"
    shortcut:
      favicon: "favicon.ico"
      type: "image/png"
      image: "logo-96.png"
    keywords: >
      education,
      learning,
      psychology
  footer:
    - icon: "lightbulb"
      href: "/session/intro"
      text: "Introduction"
    - icon: "skull"
      href: "/session/hamlet-a3-s1"
      text: "Hamlet Soliloquy"

collections_dir: content
collections:
  session:
    output: true
  segment:
    output: true

defaults:
  - scope:
      path: "*.html"
    values:
      layout: "default"
  - scope:
      type: "session"
    values:
      layout: "session"
  - scope:
      type: "segment"
    values:
      layout: "segment"
